// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "menu_items",
    columns: [
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "price", type: "int" },
      { name: "menu", type: "link", link: { table: "menus" } },
    ],
  },
  {
    name: "menus",
    columns: [
      { name: "title", type: "string" },
      { name: "description", type: "string" },
    ],
  },
  {
    name: "attractions",
    columns: [
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "image", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type MenuItems = InferredTypes["menu_items"];
export type MenuItemsRecord = MenuItems & XataRecord;

export type Menus = InferredTypes["menus"];
export type MenusRecord = Menus & XataRecord;

export type Attractions = InferredTypes["attractions"];
export type AttractionsRecord = Attractions & XataRecord;

export type DatabaseSchema = {
  menu_items: MenuItemsRecord;
  menus: MenusRecord;
  attractions: AttractionsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://webdev-s-workspace-ao95lm.eu-west-1.xata.sh/db/Chapman",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
